---
title: "QAOA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(mc.cores = parallel::detectCores())
library(rstan)
source("MA480Styles.R")
```


```{r}
file_address <- 'Noise/'
means <- read.csv(paste(file_address,"given_params.csv",sep = ""),na.strings="NA",header=FALSE)
file_address <- 'T6/'
q1 <- read.csv(paste(file_address,"Qubit1.csv",sep = ""),na.strings="NA",header=TRUE)
q2 <- read.csv(paste(file_address,"Qubit2.csv",sep = ""),na.strings="NA",header=TRUE)
# q3 <- read.csv(paste(file_address,"Qubit3.csv",sep = ""),na.strings="NA",header=TRUE)
# q4 <- read.csv(paste(file_address,"Qubit4.csv",sep = ""),na.strings="NA",header=TRUE)
```

```{stan output.var="q_model",echo = FALSE,results = "hide"}
data {
  int<lower = 0> N;
  real<lower = 0,upper = 1> y[N];
  real<lower = 0,upper = 1> x[N];
  real<lower = 0,upper = 1> gp0;
  real<lower = 0,upper = 1> gp1;
  real<lower = 0,upper = 1> geps;
}

parameters {
  real<lower = 0,upper = 1> p0;
  real<lower = 0,upper = 1> p1;
  real<lower = 0,upper = 1> eps;
  real<lower = 0> sigma;
}

model {
  sigma ~ cauchy(0,1);
  p0 ~ normal(gp0,0.1);
  p1 ~ normal(gp1,0.1);
  eps ~ normal(geps,0.01);
  
  for (i in 1:N) {
    y[i] ~ normal((0.5 + (1-eps)^200 * (x[i]-0.5)) * p0 + (0.5 - (1-eps)^200 * (x[i] - 0.5)) * (1-p1),sigma);
  }
}
```


```{r}
dataList.q1 <- list(N = nrow(q1),gp0 = means$V1[1],gp1 = means$V2[1], geps = means$V3[1], x = q1$x,y = q1$y)
dataList.q2 <- list(N = nrow(q2),gp0 = means$V1[2],gp1 = means$V2[2], geps = means$V3[2], x = q2$x,y = q2$y)
# dataList.q3 <- list(N = nrow(q3),gp0 = means$V1[3],gp1 = means$V2[3], geps = means$V3[3], x = q3$x,y = q3$y)
# dataList.q4 <- list(N = nrow(q4),gp0 = means$V1[4],gp1 = means$V2[4], geps = means$V3[4], x = q4$x,y = q4$y)
fit.q1 <- stan(model_code = q_model@model_code,data = dataList.q1,iter = 5000,warmup = 1000, control = list(adapt_delta = 0.99))
fit.q2 <- stan(model_code = q_model@model_code,data = dataList.q2,iter = 5000,warmup = 1000, control = list(adapt_delta = 0.99))
# fit.q3 <- stan(model_code = q_model@model_code,data = dataList.q3,iter = 5000,warmup = 1000, control = list(adapt_delta = 0.99))
# fit.q4 <- stan(model_code = q_model@model_code,data = dataList.q4,iter = 5000,warmup = 1000, control = list(adapt_delta = 0.99))
```

```{r}
traceplot(fit.q1,inc_warmup=FALSE)
traceplot(fit.q2,inc_warmup=FALSE)
# traceplot(fit.q3,inc_warmup=FALSE)
# traceplot(fit.q4,inc_warmup=FALSE)
```

```{r}
sampler_params <- get_sampler_params(fit.q1,inc_warmup = FALSE)
summary(do.call(rbind,sampler_params),digits=2)

sampler_params <- get_sampler_params(fit.q2,inc_warmup = FALSE)
summary(do.call(rbind,sampler_params),digits=2)
# 
# sampler_params <- get_sampler_params(fit.q3,inc_warmup = FALSE)
# summary(do.call(rbind,sampler_params),digits=2)
# 
# 
# sampler_params <- get_sampler_params(fit.q4,inc_warmup = FALSE)
# summary(do.call(rbind,sampler_params),digits=2)
```

```{r}
fit.q1
fit.q2
# fit.q3
# fit.q4
```


```{r}
df.q1 <- stan_to_df(fit.q1)
df.q2 <- stan_to_df(fit.q2)
# df.q3 <- stan_to_df(fit.q3)
# df.q4 <- stan_to_df(fit.q4)
noise_params.q1 <- data.frame(p0 = df.q1$p0,p1 = df.q1$p1, eps = df.q1$eps)
noise_params.q2 <- data.frame(p0 = df.q2$p0,p1 = df.q2$p1, eps = df.q2$eps)
# noise_params.q3 <- data.frame(p0 = df.q3$p0,p1 = df.q3$p1, eps = df.q3$eps)
# noise_params.q4 <- data.frame(p0 = df.q4$p0,p1 = df.q4$p1, eps = df.q4$eps)
```



```{r}
write.csv(noise_params.q1,paste(file_address,"StandPostQubit1.csv",sep = ""), row.names = FALSE)
write.csv(noise_params.q2,paste(file_address,"StandPostQubit2.csv",sep = ""), row.names = FALSE)
# write.csv(df.q3,paste(file_address,"StandPostQubit3.csv",sep = ""), row.names = FALSE)
# write.csv(df.q4,paste(file_address,"StandPostQubit4.csv",sep = ""), row.names = FALSE)
```























